Ascii prefix
lit/lit pull request #1959
Opened 2021-06-15 16:42 UTC by kevinpschaaf

Greek prefixes require an explicit charset on some browser/webview environments, which was causing friction.

Fixes #1958

2021-06-17 18:39 UTC, sorvell approved these changes

2021-06-17 18:39 UTC, justinfagnani approved these changes

2021-06-17 18:39 UTC, justinfagnani commented on rollup-common.js
> +const STABLE_PROPERTY_PREFIX = '$A';
I do wonder if this is unique enough...

2021-06-17 18:40 UTC, sorvell commented on rollup-common.js
> +const STABLE_PROPERTY_PREFIX = '$A';
Maybe `$lit$` for this?

2021-06-22 17:57 UTC, kevinpschaaf commented
Size increase for lit-html:
```
Before: lit-html.js   7.26 KB  7.2 KB    3.08 KB   2.79 KB  
After:  lit-html.js   7.33 KB  7.33 KB   3.07 KB   2.8 KB    
```

2021-06-22 17:58 UTC, kevinpschaaf commented on rollup-common.js
> +const STABLE_PROPERTY_PREFIX = '$A';
Added an add'l `_` to all prefixes.

2021-06-22 18:37 UTC, justinfagnani requested changes

2021-06-23 16:04 UTC, kevinpschaaf commented on .changeset/fifty-trainers-check.md
> +---
Whoops!

2021-06-29 18:25 UTC, kevinpschaaf commented
Removed pre.json and updated changelog message for this PR. @justinfagnani PTAL

2021-06-29 18:25 UTC, kevinpschaaf commented on .changeset/fifty-trainers-check.md
> +---
Updated

2021-06-29 21:15 UTC, merged