[reactive-element] Add CSP compatibility for element styles
lit/lit pull request #2134
Opened 2021-09-03 16:58 UTC by justinfagnani

This PR adds `ReactiveElement.nonceProperty` which specifies a global property to use for a CSP nonce to apply to generated `<style>` tags.

This lets an app configure a global property in app code, like:

```ts
import {ReactiveElement} from '@lit/reactive-element';
ReactiveElement.nonceProperty = 'myAppsNonce';
```

And then set a unique-per-request nonce in server-generated HTML:

```html
<script>
  window.myAppsNonce = 'abc123';
</script>
```

Which will work with a CSP policy of:

```
Content-Security-Policy: style-src 'nonce-abc123';
```

The indirection of specifying a `nonceProperty` name and a global to hold the actual nonce is needed to make it easy to have a static JS build and a per-request varying nonce value. Importing the ReactiveElement class to set the static is potentially difficult to do for bundled, non-JS-modules-using apps.

Fixes #2025

2021-09-03 17:19 UTC, samaniehsan commented
@justinfagnani  thanks for your attention to this issue. we are currently using lit elements version 1.4
What version of lit elements would support this work-around?

2021-09-03 17:21 UTC, justinfagnani commented
This would be for `lit-element@3.0` / `lit@2.0`

2021-09-07 17:37 UTC, sorvell requested changes

2021-09-07 17:37 UTC, sorvell commented on packages/reactive-element/src/css-tag.ts
> +      if (nonceProperty && (window as any)[nonceProperty]) {
```suggestion
      if (nonceProperty && (window as any)[nonceProperty] !== undefined) {
```

2021-09-07 17:37 UTC, sorvell commented on packages/reactive-element/src/reactive-element.ts
> +   * support adopted StyleSheets. To use <such style> tags with the style-src
```suggestion
   * support adopted StyleSheets. To use such <style> tags with the style-src
```

2021-09-07 18:48 UTC, sorvell commented
Would it be better from a responsibility perspective to just have something like: `window.listStyleCallback` e.g. `(style) => style;` which we call if it's defined when we're creating a style. The user would then implement this if desired and set the `nonce` as needed.  This puts the onus for actually dealing with and security the nonce with the user?

2021-09-07 19:00 UTC, justinfagnani commented
> Would it be better from a responsibility perspective to just have something like: window.litCreateStyleCallback e.g. (style) => style; which we call if it's defined when we're creating a style. The user would then implement this if desired and set the nonce as needed. This puts the onus for actually dealing with and security the nonce with the user?

The only CSP related thing they could do in such a callback is set the `nonce` attribute, so I think we should just do this for them. There's precedent in other frameworks and tools of having a global that's written to `<script>` and `<style>`. I think we should just do the simple thing like they're doing.

2021-09-08 04:48 UTC, justinfagnani commented
I limited the tests to just the reactive-element styling tests by adding a new `reactive-element-csp_test.html` file with both the CSP header added via a `<meta>` tag and a script that sets the global.

2021-09-08 04:48 UTC, justinfagnani commented
cc @arthurevans for this new feature. I need to file a docs issue still.

2021-09-08 19:08 UTC, sorvell approved these changes

2021-09-09 17:51 UTC, rictic approved these changes

2021-09-09 17:56 UTC, merged