[labs/react] Fix for #2799: add support for properties with custom accessors
lit/lit pull request #2800
Opened 2022-04-28 09:15 UTC by lideen

Hi! All new to this repo but tried to fix a bug that I found #2799

Any input appreciated 🎉

2022-05-13 16:19 UTC, justinfagnani commented
@lideen thanks for identifying this and submitting a fix and tests!

I made some comments on the implementation in the interest of speed here. I think the implementation can be collapsed into one `getInstancePropertiesOf()` function that recursively calls itself on a class's superclass, merges the superclass's properties into its own, then caches and returns the result. This will avoid materializing the prototype chain and processing prototypes multiple times. It should minimize memory allocations too.

I would like to also avoid materializing the property descriptors if possible. I think the core issue here is that accessors are not enumerable and `for...in` doesn't include non-enumerable properties. `Object.getOwnPropertyNames()` does return non-enumerable names (`Reflect.ownKeys()`) does too, but it's not supported on IE11 and we don't need Symbol-keyed properties in JSX). So I hope we can use that. It would include methods, but that might be ok.

2022-05-13 18:08 UTC, lideen commented
@justinfagnani Something like this? 1531750aedc7b4c8cbe4a39ad414fe301a496cc9

2022-05-17 21:47 UTC, justinfagnani commented
@lideen that what I was thinking at the time (though with memoizing the function).

But in the meantime I chatted with @josepharhar about it, and I think that we should match the Preact and upcoming React support for properties as much as possible. This would mean not pre-calculating the instance keys at all, but just using an `in` check on each given prop key. See https://github.com/facebook/react/blob/2c8a1452b82b9ec5ebfa3f370b31fda19610ae92/packages/react-dom/src/client/DOMPropertyOperations.js#L187-L194

2022-05-18 07:11 UTC, lideen commented
@justinfagnani I gave it a shot [79e6a4f](https://github.com/lit/lit/commit/79e6a4f793bd9cbb1dea58ca387498abe7f56844). I removed the warning about reserved props as I don't think it fits well now when the check is done on-demand 🤔 . Let me know if I should re-add it.

2022-06-15 05:50 UTC, lideen commented
@justinfagnani sorry to ping you, but is there anything I can do to move this along?

2022-08-05 18:51 UTC, justinfagnani requested changes

2022-08-05 18:51 UTC, justinfagnani commented on packages/labs/react/src/create-component.ts
> +            k in elementClass.prototype)
We still need to verify this logic (specifically excluding `k in HTMLElement.prototype`) with @josepharhar to see if it matches React 19. I'm good with going in as-is now though.

2022-08-05 18:51 UTC, justinfagnani commented on packages/labs/react/src/create-component.ts
> -        console.warn(
I think we should keep this warning. We can move this into a dev build in the future.

2022-08-11 21:10 UTC, justinfagnani commented
@lideen this has increased in urgency for us, so I'm going to try to see if I can get this in asap. Did you enable changes to your PR branch? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2022-08-11 23:53 UTC, justinfagnani approved these changes
Thanks @lideen !

I'll follow up on the comments I left with issues.

2022-08-11 23:53 UTC, merged