Remove private Lit 2 migration helpers
lit/lit pull request #2828
Opened 2022-05-03 22:26 UTC by AndrewJakubowicz

### Context

While migrating internal to Lit 2, we had these additional options to change how the `render` function behaved. However these are no longer required as they are not referenced internally.

### Testing

Tested internally with a TGP using the same change, and checking for all references of `INTERNAL` and `clearContainerForLit2MigrationOnly`.

I also removed a unit test that was testing the `INTERNAL` and `clearContainerForLit2MigrationOnly` option behavior.

2022-05-03 23:15 UTC, rictic approved these changes
Awesome work!

2022-05-04 22:58 UTC, justinfagnani requested changes

2022-05-04 22:58 UTC, justinfagnani commented on packages/lit-html/src/test/lit-html_test.ts
> +        `${clearedHtml}<p>HELLO</p>${remainingHtml}`
You can remove this whole test now.

2022-05-04 23:00 UTC, AndrewJakubowicz commented on packages/lit-html/src/test/lit-html_test.ts
> +        `${clearedHtml}<p>HELLO</p>${remainingHtml}`
Done! Good point!

2022-05-04 23:39 UTC, justinfagnani approved these changes

2022-05-05 01:10 UTC, merged