chore(contributing): change lit-html to lit
lit/lit pull request #2874
Opened 2022-05-11 19:26 UTC by njfamirm

Just change `lit-html` to `lit` in CONTRIBUTING.md

2022-05-13 15:47 UTC, justinfagnani requested changes
Thanks for the fix!

We capitalize Lit though. After fixing that this look good.

2022-05-13 15:47 UTC, justinfagnani commented on CONTRIBUTING.md
> +Thank you for your interest in contributing to lit!
Capitalize Lit here and the two places below.

2022-05-13 16:37 UTC, justinfagnani approved these changes

2022-05-13 16:37 UTC, merged

2022-05-13 16:37 UTC, justinfagnani commented
Thanks!

2022-05-13 16:54 UTC, njfamirm commented
> Thanks!

You're welcome

2022-08-10 12:56 UTC, AliMD commented
👍🏻