[labs/analyzer] Adds support for analyzing JavaScript packages
lit/lit pull request #3304
Opened 2022-09-26 08:59 UTC by kevinpschaaf

* Removed the automatic tsconfig file lookup in the `packageRoot` to instead require `packageRoot` to _either_ point to a tsconfig file, or else a package root containing a `tsconfig.json`; if none is found, we assume a JS program. This avoids `ts.findConfigFile` from searching to the root of your hard disk when analyzing a JS program; seems better to be explicit anyway.
* If no tsconfig is found, we create a barebones TS program using `allowJS` and a glob of all `*.js` within the `packageRoot`
* Added support for JS-specific analysis:
  * `customElements.define()`
  * `static properties = {...}` and `static get properties() { return {...} }`
  * Inference of types initialized in the constructor (note even in a JS program, TS does a decent job at inference)
  * Types on the `ReactiveProperty` model is now optional in case there is no initializer we can even infer `any` from
  * Add `isOptional` and `isNonNull` to the `ReactiveProperty` model (based on `?` and `!` post-fix operators on the declarations, or a best-effort JS fallback); this info was being used in the Vue generator
* Duplicate / de-TypeScript-ify all the `test-files` (input source for tests) under separate `js` / `ts` folders
* Run all the unit tests in `for (const lang of ['js', 'ts'])` loop

2022-09-27 12:30 UTC, sorvell requested changes

2022-09-27 12:30 UTC, sorvell commented on packages/labs/analyzer/src/test/analyzer_test.ts
> +  const getSourceFilename = (f: string) =>
Pull these out into test utilities?

2022-09-28 22:10 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +  // from which we can infer types from. This is the primary path that JS source
I can try and clarify in the comment. Assuming native "use define for class field semantics", you can't initialize the property using a native field initializer, you need to do it in the constructor. However, You _can't_ do that in TypeScript without also having a `declare foo: string` or whatever, so this extra "look in the constructor" path is _primarily_ for JS initializers of reactive properties.

If a JS user disabled the "use define for class fields" in their compiler, then they will already have entries in the `undecoratedProperties` map (and we don't overwrite that with constructor initializers).

2022-09-28 23:13 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/analyze-package.ts
> +  // This logic accepts either a path to folder containing a tsconfig.json
Done

2022-09-28 23:13 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/analyze-package.ts
> +          module: 'esm',
No, will add a TODO; should probably be configurable.

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/analyzer.ts
> +    const packageRoot = getPackageRootForModulePath(
DOne

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/lit-element.ts
> +    declaration.parent.forEachChild((child) => {
Done

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +      undecoratedProperties.set(name, prop);
Yeah, nice catch. Done.

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +  const object = getStaticPropertiesObjectLiteral(properties);
Yes

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +      const nodeForType = undecoratedProperties.get(name);
Fixed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +      // with a ctor initializer as non-null and optional; in TS when we have
Removed, as discussed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +          : true;
Removed, as discussed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +          ? false
Removed, as discussed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +    const statement = properties.body?.statements[0];
Done.

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +      if (
Done

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/model.ts
> +   * In JavaScript, properties that are initialized in the constructor
Removed, as discussed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/lib/lit-element/properties.ts
> +          ? !!nodeForType.exclamationToken
Removed, as discussed

2022-09-28 23:14 UTC, kevinpschaaf commented on packages/labs/analyzer/src/test/analyzer_test.ts
> +  const getSourceFilename = (f: string) =>
Done

2022-09-28 23:22 UTC, kevinpschaaf commented on packages/labs/analyzer/test-files/js/basic-elements/element-a.js
> +    this.b = 1;
Done

2022-09-29 20:46 UTC, sorvell approved these changes
LGTM

2022-09-30 16:58 UTC, merged