[labs/virtualizer] handle uninitialized layout in _childrenSizeChanged
lit/lit pull request #3708
Opened 2023-03-07 08:52 UTC by megheaiulian

Handle uninitialized layout in `_childrenSizeChanged`.

 Because the ResizeObserver starts listening very early it is possible that the layout has not been imported and initialized when a children has updated.

Fixes #3726

2023-03-07 20:20 UTC, usergenic commented
Seems totally plausible.  Thanks for the fix, @megheaiulian

2023-03-07 20:22 UTC, justinfagnani commented
@megheaiulian it would be great to have a test to prevent a regression here.

2023-03-07 20:32 UTC, usergenic commented
The scenario where this would create a regression would be that the logic is relying on a weird unhandled runtime error to abort execution of the main childrenSizeChanged callback.  With or without this fix, the inner condition doesn't execute, but the "new" behavior is that code continues to execute without runtime error and invokes this._scheduleLayoutComplete(); etc--

I'll investigate the observer instantiation in relation to a deferred/dynamic layout assignment and see if there's a reason why this would behavior would be unwanted.

2023-03-07 20:34 UTC, usergenic commented
i.e. it is an open question is whether this either creates a regression or fixes an edge case.

2023-03-09 16:45 UTC, graynorton commented
Thanks for the PR, @megheaiulian!

A simplified repro case would definitely be helpful; at minimum, could you file an issue to match up with this PR?

@usergenic @justinfagnani There are unreleased changes in virtualizer that seem quite likely to be relevant, as they definitely touch (and aim to simplify) virtualizer initialization. Is there anything holding up a release? In any case, once we have a repro for this, we should make sure that it still holds when run against the code in `main`.

2023-03-09 16:48 UTC, megheaiulian commented
@graynorton I will add a test for this.

2023-03-14 18:07 UTC, megheaiulian commented
Add a test case to reproduce the error.

2023-03-31 06:24 UTC, megheaiulian commented
@usergenic Could you please have a another look at this ? It is a very annoying little bug.

2023-03-31 13:50 UTC, justinfagnani requested changes
Looks good after the lint fix!

2023-03-31 13:50 UTC, justinfagnani commented on packages/labs/virtualizer/src/test/scenarios/immediate-sizing.test.ts
> +    const example: ImmediateSizing = await fixture(
This is causing a lint warning. Just don't declare a variable.

2023-04-13 06:12 UTC, usergenic approved these changes
Thank you for your patience on this and for adding the test case etc.  LGTM

2023-04-13 06:13 UTC, usergenic commented
@justinfagnani this PR needs your approval because of prior requested change.

2023-04-17 18:58 UTC, justinfagnani approved these changes

2023-04-18 19:32 UTC, merged

2023-04-18 19:33 UTC, usergenic commented
@megheaiulian alright this is finally merged.  Thanks again!