Add separate entrypoint for createPackageAnalyzer
lit/lit pull request #3980
Opened 2023-06-25 00:05 UTC by justinfagnani

Previously `index.ts` imported both the main `Analyzer` class and `createPackageAnalyzer()`, which uses Node APIs.

This PR separates the entrypoints into `index.ts` which only exports the Analyzer class and model interfaces, and `package-analyzer.ts` which exports all of that, plus `createPackageAnalyzer()`.

This is a breaking change.

2023-06-27 23:55 UTC, rictic requested changes
Build is failing

2023-06-27 23:55 UTC, rictic commented on packages/labs/analyzer/package.json
> +    "./package-analyzer.js": "./package-analyzer.js"
package-analyzer.js or analyze-package.js?

2023-07-11 18:41 UTC, kevinpschaaf approved these changes
LGTM, modulo the naming issue @rictic raised. Did you want the top-level import to be `package-analyzer.js` to match `analyzer.js`? If so, need to rename the file, otherwise rename the `exports` in package.json.

2023-07-18 00:51 UTC, justinfagnani commented
Argh. I don't understand why the build is failing on CI now. Build and tests are passing on my machine even after a git clean. I also don't understand why it was _passing_ on my machine earlier as I had some obviously bad imports.

2023-07-19 16:24 UTC, rictic approved these changes

2023-07-19 16:24 UTC, merged