[labs/task] Fix Task.render()'s return type always being undefined
lit/lit pull request #4070
Opened 2023-08-04 01:05 UTC by mlcui-google

In TypeScript:
- `unknown` is the top type: everything can be assigned to `unknown`, and `unknown` can be only assigned to `unknown`.
- `never` is the bottom type: `never` can be assigned to everything, and only `never` can be assigned to `never`.
- Assuming a `Cat` can be assigned to an `Animal`, but not the other way around:
  - (read-only) arrays are covariant: a `Cat[]` can be assigned to an `Animal[]`, but not the other way around. In other words, arrays don't change the "order" of types, as expected.
  - function arguments are contravariant: a `(x: Animal) => boolean` can be assigned to a `(x: Cat) => boolean`, but not the other way around. In other words, function arguments flip the "order" of types.

The right-hand of the `extends` in `MaybeReturnType` is a `(...args: unknown[]) => ?`. If `(...args: T[]) => ?` is assignable to that, then `unknown` is assignable to `T`… but `unknown` can only be assigned to `unknown`, so `T` must be `unknown`. No functions can be assigned to a type of `(...args: unknown[]) => ?` unless it is also that type.

Therefore, the `extends` clause in `MaybeReturnType` was always failing for all functions, apart from the ones which had an arguments array of `unknown[]`. This caused `render`'s return type to only include `undefined`.

The function type in `MaybeReturnType` should be a function type which can have _any_ function arguments, so we should use `(...args: never[]) => ?` instead - as `never` can be assigned to everything, so everything can be assigned to `(...args: never[]) => ?`.

2023-08-04 03:19 UTC, rictic approved these changes

2023-08-04 03:20 UTC, mlcui-google commented
@rictic Does this need a changeset?

2023-08-04 03:26 UTC, rictic commented
Yes, run `npm run changeset` to create one. I think this is a bug fix, so this would count as a patch change (not a major or minor)

2023-08-04 03:30 UTC, mlcui-google commented
Done (as a new commit). I assume this PR will be squashed when merged - let me know if you'd like me to squash it on my branch.

2023-08-04 06:32 UTC, rictic commented
Yep, will squash and merge!

2023-08-04 17:08 UTC, justinfagnani requested changes
We need to update the test associated with this too: https://github.com/lit/lit/blob/main/packages/labs/task/src/test/task_test.ts#L1029

The current test is intended to show that `render()` does return a type based on the callback return types - which it does now because the callbacks have no arguments and so can be assigned to `(...args: unknown[]) => ?`.

I think the only change needed to show the typing failing is to add an argument to the `complete` callback in the last assertion:

```diff
    accept<number>(
      el.task.render({
        initial: () => 123,
-        complete: () => 123,
+        complete: (x: string) => Number(x),
        pending: () => 123,
        error: () => 123,
      })
    );
```

2023-08-07 00:26 UTC, mlcui-google commented
Done. A new type-only test was added to test for this, which fails if the change is reverted.

2023-08-10 20:43 UTC, justinfagnani approved these changes

2023-08-10 20:43 UTC, merged

2023-08-10 20:44 UTC, justinfagnani commented
Thanks a lot @mlcui-google!